#---------COMANDOS PARA RODAR A CI LOCALMENTE, E EXTRAIR O RESULTADO DOS TESTES---------
# docker-compose -f docker-compose.ci.yml up --force-recreate --build --abort-on-container-exit
# docker create --name xpto -v docker.dotnet.samples-test-results:/TestResults busybox
# docker cp xpto:./TestResults D:\TestResults
# docker rm xpto
# docker-compose -f docker-compose.ci.yml down --rmi all -v --remove-orphans
version: '3.5'

services:
  tjmt.docker.dotnet.samples.data:
    image: tjmt/docker.dotnet.samples.data:latest
    ports:
      - 1433:1433    
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@ssw0rd
      DATABASE: Banco 

  tjmt.docker.dotnet.samples:
    image: tjmt.docker.dotnet.samples
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        CONFIGURATION: "Release"
        SOLUTION_NAME: "TJMT.Docker.DotNet.Samples.sln"
    entrypoint: ["/entrypoint-ci/wait-for-it.sh", "tjmt.docker.dotnet.samples.data:1433", "--", "/entrypoint-ci/continuous-integration.sh"]
    environment:
      SGDB: 'SQLSERVER'
      CONNECTION_STRING: 'Server=tjmt.docker.dotnet.samples.data,1433;Database=Banco;User Id=sa;Password=P@ssw0rd;'
      ASPNETCORE_ENVIRONMENT: 'Development'
      PROJECT_NAME: tjmt.docker.dotnet.samples
      PROJECT_VERSION: "20181108.4" #Informar pela automação $(Build.BuildNumber)
      HOST: "http://localhost"  #Informar pela automação $(HOST)
      SONAR_LOGIN: "token" #Informar pela automação $(SONAR_LOGIN), opcional, informar quando deseja que o CI analise o código pelo sonarQube
      SONAR_HOST_URL: "url" #Informar pela automação $(SONAR_HOST_URL), opcional, informar quando deseja que o CI analise o código pelo sonarQube
      COVERAGE_PATH: "/TestResults/codecoverage" #OPCIONAL
      RESULT_PATH: "/TestResults/result" #OPCIONAL
    depends_on: 
      - tjmt.docker.dotnet.samples.data      
    volumes:
      - test-result:/TestResults

volumes:
  test-result:
    name: "docker.dotnet.samples-test-results" #Informar pela automação $(DOCKER_VOLUME_NAME)

networks:
  default:
    name: ns-tjmt-docker-dotnet-samples-ci