version: '3.5'

services:
  tjmt.docker.dotnet.samples:
    ports:
      - 5555:80
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      CONNECTION_STRING: 'Server=tjmt.docker.dotnet.samples.data,1433;Database=Banco;User Id=sa;Password=P@ssw0rd;'

  tjmt.docker.dotnet.samples.data:
    image: tjmt.docker.dotnet.samples.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 1433:1433    
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@ssw0rd
      DATABASE: Banco 