# dotnet test test/TJMT.Docker.DotNet.Samples.Test --no-build -c Release -r "/TestResults/result/" -l "trx;LogFileName=TJMT.Docker.DotNet.Samples.Test.trx"
# coverlet test/TJMT.Docker.DotNet.Samples.Test/bin/Release/netcoreapp2.1/TJMT.Docker.DotNet.Samples.Test.dll --target "dotnet" --targetargs "test test/TJMT.Docker.DotNet.Samples.Test --no-build -c Release" --format opencover --format cobertura --output "/TestResults/codecoverage/TJMT.Docker.DotNet.Samples.Test/"

# docker-compose -f docker-compose.ci.yml up --force-recreate --build --abort-on-container-exit
# docker create --name xpto -v docker.dotnet.samples-test-results:/TestResults busybox
# docker cp xpto:./TestResults D:\TestResults
# docker rm xpto
# docker-compose -f docker-compose.ci.yml down --rmi all -v --remove-orphans
version: '3.5'

services:
  tjmt.docker.dotnet.samples.data:
    image: tjmt/docker.dotnet.samples.data:latest
    ports:
      - 1433:1433    
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@ssw0rd
      DATABASE: Banco 

  tjmt.docker.dotnet.samples:
    image: tjmt.docker.dotnet.samples
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        CONFIGURATION: "Release"
        SOLUTION_NAME: "TJMT.Docker.DotNet.Samples.sln"
    entrypoint: ["/entrypoint-ci/wait-for-it.sh", "tjmt.docker.dotnet.samples.data:1433", "--", "/entrypoint-ci/continuous-integration.sh"]
    environment:
      SGDB: 'SQLSERVER'
      CONNECTION_STRING: 'Server=tjmt.docker.dotnet.samples.data,1433;Database=Banco;User Id=sa;Password=P@ssw0rd;'
      ASPNETCORE_ENVIRONMENT: 'Development'
      HOST: "http://localhost"  
      PROJECT_NAME: tjmt.docker.dotnet.samples
      PROJECT_VERSION: "20181108.4"
      SONAR_LOGIN: "token"
      SONAR_HOST_URL: "url"
      COVERAGE_PATH: "/TestResults/1/codecoverage"
      RESULT_PATH: "/TestResults/1/result"
    depends_on: 
      - tjmt.docker.dotnet.samples.data      
    volumes:
      - test-result:/TestResults

volumes:
  test-result:
    name: "docker.dotnet.samples-test-results"

networks:
  default:
    name: ns-tjmt-docker-dotnet-samples-ci