# docker-compose -f docker-compose.build.yml build --no-cache
# docker-compose -f docker-compose.build.yml push
# docker-compose -f docker-compose.build.yml down --rmi all -v --remove-orphans
version: '3.5'

services:
  tjmt.docker.dotnet.samples:
    image: tjmt/docker.dotnet.samples
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        CONFIGURATION: "Release"
        SOLUTION_NAME: "TJMT.Docker.DotNet.Samples.sln"
        PATH_SOLUTION_NAME: "TJMT.Docker.DotNet.Samples.sln"
        PATH_PROJECT_1: "src/TJMT.Docker.DotNet.Samples/TJMT.Docker.DotNet.Samples.csproj"
        PATH_PROJECT_2: "src/TJMT.Docker.DotNet.Samples.Core/TJMT.Docker.DotNet.Samples.Core.csproj"