version: '3.5'

services:
  tjmt.docker.dotnet.samples:
    image: tjmt.docker.dotnet.samples
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        CONFIGURATION: "Release"