# docker-compose -f docker-compose.build.yml build
# docker-compose -f docker-compose.build.yml push
# docker-compose -f docker-compose.build.yml down --rmi all -v --remove-orphans
version: '3.5'

services:
  sistema-api-tjmt-jus-br:
    image: ${REGISTRY}dotnet-samples:${PROJECT_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        CONFIGURATION: "Release"      