# docker-compose -f docker-compose.build.yml build
# docker-compose -f docker-compose.build.yml push
# docker-compose -f docker-compose.build.yml down --rmi all -v --remove-orphans
version: '3.5'

services:
  tjmt.docker.dotnet.samples.data:
    image: tjmt/docker.dotnet.samples.data:latest
    build: 
      context: .
      dockerfile: Dockerfile